/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectotienda;

import java.security.MessageDigest;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sirias Cano
 */
public class frmSistemaTienda extends javax.swing.JFrame {

    
    
    /**
     * Creates new form frmSistemaTienda
     */
    public frmSistemaTienda() {
        initComponents();
        this.tabledetalles.setModel(modelo);
        this.modelo.addColumn("T. DE PAGO");
        this.modelo.addColumn("GÉNERO");
        this.modelo.addColumn("TALLAS");
        this.modelo.addColumn("PRENDAS");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("PRECIO UNITARIO");
        this.modelo.addColumn("PRECIO");
        
        this.tabladetallesp.setModel(modelo2);
        this.modelo2.addColumn("PRODUCTO");
        this.modelo2.addColumn("CANTIDAD");
        this.modelo2.addColumn("PRECIO UNITARIO");
        this.modelo2.addColumn("PRECIO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbotpago = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        botonh = new javax.swing.JRadioButton();
        botonm = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbotallas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtprenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btngenerar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledetalles = new javax.swing.JTable();
        btnlimpiartabla = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        btnnetopagar = new javax.swing.JButton();
        txtnetopagar = new javax.swing.JTextField();
        btnReport = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtcantidadp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtpreciop = new javax.swing.JTextField();
        btngenerarp = new javax.swing.JButton();
        btnlimpiarp = new javax.swing.JButton();
        txttotalp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladetallesp = new javax.swing.JTable();
        btnlimpiartablap = new javax.swing.JButton();
        btnquitarp = new javax.swing.JButton();
        btnreportp = new javax.swing.JButton();
        btnnetopagarp = new javax.swing.JButton();
        txtnetopagarp = new javax.swing.JTextField();
        btnAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE CAJERO  - TIENDA EM");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos y Descuentos Aplicados"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Descuentos Tarjeta (Solo en Ropa)");

        jLabel3.setText("Hombre Talla S=10% ");

        jLabel4.setText("Mujer Talla S=7%");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Productos de Cuido Personal y Belleza");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Productos para el Cabello:");

        jLabel22.setText("Acondicionador = C$80");

        jLabel23.setText("Shampoo Anticaida = C$90");

        jLabel24.setText("Shampoo Caspa = C$80");

        jLabel25.setText("Gel para Cabello = C$70");

        jLabel26.setText("Crepa para Cabello = C$80");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Productos para Cuido Corporal:");

        jLabel28.setText("Hidratante Corporal = C$120");

        jLabel29.setText("Exfoliante Corporal = C$130");

        jLabel30.setText("Desmaquillante = C$100");

        jLabel31.setText("Protector Solar = C$120");

        jLabel32.setText("Hidratante Labial = C$110");

        jLabel33.setText("Crema de manos = C$120");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Productos de Belleza:");

        jLabel35.setText("Labiales = C$70 / C$80");

        jLabel36.setText("Sombras = C$100");

        jLabel37.setText("Esmalte = C$90");

        jLabel38.setText("Rimel = C$80");

        jLabel39.setText("Rubor = C$100");

        jLabel5.setText("Hombre Talla M=10% ");

        jLabel6.setText("Hombre Talla L=12% ");

        jLabel7.setText("Hombre Talla XL = 14% ");

        jLabel15.setText("Mujer Talla M=7%");

        jLabel40.setText("Mujer Talla  L=12%");

        jLabel41.setText("Mujer Talla XL=14%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel40))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel41))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Compra de Ropa"));

        jLabel8.setText("Tipo de Pago:");

        cbotpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Tarjeta", "Efectivo" }));

        jLabel9.setText("Género:");

        buttonGroup1.add(botonh);
        botonh.setText("Hombre");
        botonh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonhActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonm);
        botonm.setText("Mujer");

        jLabel10.setText("Tallas:");

        cbotallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "S", "M", "L", "XL" }));

        jLabel11.setText("Prenda:");

        txtprenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprendaActionPerformed(evt);
            }
        });

        jLabel12.setText("Cantidad:");

        jLabel13.setText("Precio:");

        jLabel14.setText("Total a Pagar:");

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        btngenerar.setText("Generar Compra");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel9)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel10)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbotpago, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnlimpiar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btngenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbotpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonh)
                    .addComponent(botonm)
                    .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnlimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btngenerar))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Compras de Ropa"));

        tabledetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabledetalles);

        btnlimpiartabla.setText("Limpiar Tabla");
        btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablaActionPerformed(evt);
            }
        });

        btnquitar.setText("Quitar Compra");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        btnnetopagar.setText("Neto a Pagar");
        btnnetopagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetopagarActionPerformed(evt);
            }
        });

        btnReport.setText("Reporte");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlimpiartabla)
                .addGap(18, 18, 18)
                .addComponent(btnquitar)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addGap(18, 18, 18)
                .addComponent(btnnetopagar)
                .addGap(18, 18, 18)
                .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiartabla)
                    .addComponent(btnquitar)
                    .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport)
                    .addComponent(btnnetopagar))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Compra de Productos"));

        jLabel16.setText("Producto:");

        jLabel17.setText("Cantidad:");

        jLabel18.setText("Precio:");

        btngenerarp.setText("Generar Compra");
        btngenerarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarpActionPerformed(evt);
            }
        });

        btnlimpiarp.setText("Limpiar");
        btnlimpiarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarpActionPerformed(evt);
            }
        });

        txttotalp.setEditable(false);
        txttotalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalpActionPerformed(evt);
            }
        });

        jLabel19.setText("Total a Pagar:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnlimpiarp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtproducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btngenerarp, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel18))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtcantidadp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtpreciop, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttotalp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidadp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpreciop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlimpiarp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenerarp)
                    .addComponent(txttotalp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de Compra de Productos"));

        tabladetallesp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabladetallesp);

        btnlimpiartablap.setText("Limpiar");
        btnlimpiartablap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablapActionPerformed(evt);
            }
        });

        btnquitarp.setText("Quitar Compra");
        btnquitarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarpActionPerformed(evt);
            }
        });

        btnreportp.setText("Reporte");
        btnreportp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportpActionPerformed(evt);
            }
        });

        btnnetopagarp.setText("Neto a Pagar");
        btnnetopagarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetopagarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnlimpiartablap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnquitarp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreportp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnetopagarp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnetopagarp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiartablap)
                    .addComponent(btnquitarp)
                    .addComponent(btnreportp)
                    .addComponent(btnnetopagarp)
                    .addComponent(txtnetopagarp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnAbout.setText("Acerca De");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    private void botonhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonhActionPerformed

    private void txtprendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprendaActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        this.cbotpago.setSelectedIndex(0);
        if(botonh.isSelected()){
            
        }
        if(botonm.isSelected()){
            
        }
        this.cbotallas.setSelectedIndex(0);
        this.txtcantidad.setText("");
        this.txtprecio.setText("");
        this.txttotal.setText("");
        this.txtprenda.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        pago_hombres_efectivo();
        pago_mujeres_efectivo();
        descuentos_hombres_tarjeta();
        descuentos_mujeres_tarjeta();
        
        if(botonh.isSelected()){
            this.modelo.addRow(new Object[]{this.cbotpago.getSelectedItem(),"Hombre", 
            this.cbotallas.getSelectedItem(), this.txtprenda.getText(), this.txtcantidad.getText(),
            this.txtprecio.getText(), this.txttotal.getText()});        
        }
        else if(botonm.isSelected()){
            this.modelo.addRow(new Object[]{this.cbotpago.getSelectedItem(),"Mujer", 
            this.cbotallas.getSelectedItem(), this.txtprenda.getText(), this.txtcantidad.getText(),
            this.txtprecio.getText(), this.txttotal.getText()}); 
        }
    }//GEN-LAST:event_btngenerarActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        modelo.removeRow(this.tabledetalles.getSelectedRow());
    }//GEN-LAST:event_btnquitarActionPerformed

    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        int x = this.modelo.getRowCount();
        for(int y = 0; y<=x; y++){
            this.modelo.removeRow(0);
        }
        this.txtnetopagar.setText("");
    }//GEN-LAST:event_btnlimpiartablaActionPerformed

    private void btnnetopagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetopagarActionPerformed
       double sumatoria;
       double sumatorial = 0;
       int totalrow = tabledetalles.getRowCount();
       totalrow-=1;
       for(int i=0; i<=(totalrow);i++){
           sumatoria = Double.parseDouble(String.valueOf(tabledetalles.getValueAt(i, 6)));
           sumatorial += sumatoria;
       }
       txtnetopagar.setText("C$"+String.valueOf(sumatorial));
    }//GEN-LAST:event_btnnetopagarActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("-- Productos Comprados --");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        
        try{
            tabledetalles.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnlimpiarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarpActionPerformed
        // TODO add your handling code here:
        this.txtcantidadp.setText("");
        this.txtpreciop.setText("");
        this.txttotalp.setText("");
        this.txtproducto.setText("");
    }//GEN-LAST:event_btnlimpiarpActionPerformed

    private void btngenerarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarpActionPerformed
        // TODO add your handling code here:
            pago_de_productos();
            this.modelo2.addRow(new Object[]{this.txtproducto.getText(), this.txtcantidadp.getText(), this.txtpreciop.getText(),
            this.txttotalp.getText()});
        
    }//GEN-LAST:event_btngenerarpActionPerformed

    public void pago_de_productos(){
        double producto_p;
        double producto_c;
        double producto_t;
        double iva_p = 0.15;
        
        producto_c = Double.parseDouble(this.txtcantidadp.getText());
        producto_p = Double.parseDouble(this.txtpreciop.getText());
        producto_t = ((producto_p * producto_c) + ((producto_p * producto_c)*iva_p));
        this.txttotalp.setText(String.valueOf(producto_t));
    }
    
    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txttotalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalpActionPerformed

    private void btnlimpiartablapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablapActionPerformed
        // TODO add your handling code here:
        int x = this.modelo2.getRowCount();
        for(int y = 0; y<=x; y++){
            this.modelo2.removeRow(0);
        }
        this.txtnetopagarp.setText("");
    }//GEN-LAST:event_btnlimpiartablapActionPerformed

    private void btnquitarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarpActionPerformed
        // TODO add your handling code here:
        modelo2.removeRow(this.tabladetallesp.getSelectedRow());
    }//GEN-LAST:event_btnquitarpActionPerformed

    private void btnnetopagarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetopagarpActionPerformed
        // TODO add your handling code here:
       double sumatoria1;
       double sumatoria2 = 0;
       int totalrow2 = tabladetallesp.getRowCount();
       totalrow2-=1;
       for(int i=0; i<=(totalrow2);i++){
           sumatoria1 = Double.parseDouble(String.valueOf(tabladetallesp.getValueAt(i, 3)));
           sumatoria2 += sumatoria1;
       }
       txtnetopagarp.setText("C$"+String.valueOf(sumatoria2));
    }//GEN-LAST:event_btnnetopagarpActionPerformed

    private void btnreportpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportpActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("-- Productos Comprados --");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        
        try{
            tabladetallesp.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnreportpActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
            About frm = new About();
            frm.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnAboutActionPerformed
    public void pago_hombres_efectivo(){
        double cantidad_s, precio_s, total_s;
        double cantidad_m, precio_m, total_m; 
        double cantidad_l, precio_l, total_l;
        double cantidad_xl, precio_xl, total_xl;
        double iva_c = 0.15;
        
        //SI SELECCIONA S
        if(cbotpago.getSelectedIndex() == 2){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = ((precio_s * cantidad_s)) + ((cantidad_s * precio_s)*iva_c);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
            //SI SELECCIONA M
            if(cbotpago.getSelectedIndex() == 2){
                if(this.botonh.isSelected()){
                    if(cbotallas.getSelectedIndex()==2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m) + ((cantidad_m * precio_m)*iva_c);
                    this.txttotal.setText(String.valueOf(total_m));
                    }
                }
            }
            //SI SELECCIONA L
            if(cbotpago.getSelectedIndex() == 2){
                if(this.botonh.isSelected()){
                    if(cbotallas.getSelectedIndex()==3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l) + ((cantidad_l * precio_l)*iva_c);
                    this.txttotal.setText(String.valueOf(total_l));
                    }
                }
            }
            //SI SELECCIONA XL
            if(cbotpago.getSelectedIndex() == 2){
                if(this.botonh.isSelected()){
                    if(cbotallas.getSelectedIndex()==4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl) + ((cantidad_xl * precio_xl)*iva_c);
                    this.txttotal.setText(String.valueOf(total_xl));
                    }
                }
            }
        }
       
    }
    public void pago_mujeres_efectivo(){
        double cantidad_s, precio_s, total_s;
        double cantidad_m, precio_m, total_m; 
        double cantidad_l, precio_l, total_l;
        double cantidad_xl, precio_xl, total_xl;
        double iva_c = 0.15;
        
        //SI SE SELECCIONA S
        if(cbotpago.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s) + ((cantidad_s * precio_s)*iva_c);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SI SELECCIONA M
        if(cbotpago.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m) + ((cantidad_m * precio_m)*iva_c);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SI SELECCIONA L
        if(cbotpago.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l) + ((cantidad_l * precio_l)*iva_c);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }
        //TALLA XL
        if(cbotpago.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl)  + ((cantidad_xl * precio_xl)*iva_c);
                    this.txttotal.setText(String.valueOf(total_xl));
                }
            }
        }
        
    }
    public void descuentos_mujeres_tarjeta(){
        double cantidad_s, precio_s, total_s, desc_s = 0.07;
        double cantidad_m, precio_m, total_m, desc_m = 0.07;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        double cantidad_xl, precio_xl, total_xl, desc_xl = 0.14;
        double iva_c = 0.15;
        
        //SI SE SELECCIONA S
        if(cbotpago.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s)*desc_s) + ((cantidad_s * precio_s)*iva_c);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SI SE SELECCIONA M
        if(cbotpago.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m)*desc_m) + ((cantidad_m * precio_m)*iva_c);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SI SE SELECCIONA L
        if(cbotpago.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l)*desc_l)+((cantidad_l * precio_l)*iva_c);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }
        //SI SE SELECCIONA XL
        if(cbotpago.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl)-((cantidad_xl * precio_xl)*desc_xl) + ((cantidad_xl * precio_xl)*iva_c);
                    this.txttotal.setText(String.valueOf(total_xl));
                }
            }
        }
    }
    public void descuentos_hombres_tarjeta(){
        double cantidad_s, precio_s, total_s, desc_s = 0.10;
        double cantidad_m, precio_m, total_m, desc_m = 0.10;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        double cantidad_xl, precio_xl, total_xl, desc_xl = 0.14;
        double iva_c = 0.15;
        
        //SI SE SELECCIONA S
        if(cbotpago.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s)*desc_s) + ((cantidad_s * precio_s)*iva_c);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        
        //SI SE SELECCIONA M
        if(cbotpago.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m)*desc_m) + ((cantidad_m * precio_m)*iva_c);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
         }
        //SI SE SELECCIONA L
        if(cbotpago.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l)*desc_l) + ((cantidad_l * precio_l)*iva_c);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
         }
        //SI SE SELECCIONA XL
        if(cbotpago.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl)-((cantidad_xl * precio_xl)*desc_xl) + ((cantidad_xl * precio_xl)*iva_c);
                    this.txttotal.setText(String.valueOf(total_xl));
                }
            }
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSistemaTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonh;
    private javax.swing.JRadioButton botonm;
    private javax.swing.JButton btnAbout;
    private javax.swing.JToggleButton btnReport;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btngenerarp;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiarp;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JButton btnlimpiartablap;
    private javax.swing.JButton btnnetopagar;
    private javax.swing.JButton btnnetopagarp;
    private javax.swing.JButton btnquitar;
    private javax.swing.JButton btnquitarp;
    private javax.swing.JButton btnreportp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbotallas;
    private javax.swing.JComboBox<String> cbotpago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabladetallesp;
    private javax.swing.JTable tabledetalles;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcantidadp;
    private javax.swing.JTextField txtnetopagar;
    private javax.swing.JTextField txtnetopagarp;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtpreciop;
    private javax.swing.JTextField txtprenda;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalp;
    // End of variables declaration//GEN-END:variables
}
